name: flutter_beep
description: A very lite module to play system sounds and beep for flutter apps (no sound files)
version: 0.3.0
repository: https://github.com/trietho/flutter_beep
homepage: https://github.com/trietho/flutter_beep

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gonoter.flutter_beep
        pluginClass: FlutterBeepPlugin
      ios:
        pluginClass: FlutterBeepPlugin
